#!/bin/bash
export LANG='en_US.UTF-8'

color_primary=${color_primary:="36"}
color_secondary=${color_secondary:="35"}
color_danger=${color_danger:="38;5;1"}
color_warning=${color_warning:="38;5;11"}
color_success=${color_success:="38;5;10"}

# Declare array of services and pretty human readable names
declare -a services=(
"pihole-FTL"
"wg-quick@wg0"
"nginx"
"unbound"
)
declare -a serviceName=(
"Pi-Hole"
"PiVPN"
"nginx"
"unbound"
)
declare -a serviceStatus=()

# Get status of all my services
for service in "${services[@]}"
do
    serviceStatus+=($(systemctl is-active "$service.service"))
done

# Maximum column width
width=$((34))

# Current line and line length
line=""
lineLen=0

echo -e "\e[${color_primary}mServices running:\e[0m"

for i in ${!serviceStatus[@]}
do
    # Color the next line green if it's active, else red
    if [[ "${serviceStatus[$i]}" == "active" ]]; then
        line+="\e[${color_success}m●\e[0m ${serviceName[$i]} "
    else
        line+="\e[1;${color_warning}m▲\e[0m ${serviceName[$i]} "
    fi
done

# echo what is left
echo -e "$line"
