#!/bin/bash

status=$(cat /sys/class/power_supply/BAT1/status)
current_percent=$(cat /sys/class/power_supply/BAT1/capacity)

if [[ $status = "Charging" ]]
then
    exit
fi

if [[ $current_percent -eq 80 ]]
then
    telegram-notify 'Server running on battery.' 'Currently at 80%.'
elif [[ $current_percent -eq 40 ]]
then
    telegram-notify 'Battery running low!' '40% left!'
elif [[ $current_percent -eq 20 ]]
then
    telegram-notify 'Battery at critical level!' "20% left! If you won't plug in now server will shutdown!"
fi
